# Анализ топ 200 YouTube-блогеров

<b>Словарь данных:</b>

 - Country: Name of the country ('IN', 'US', 'KR', 'CA', 'BR', 'MX', 'SV', 'CL', 'NO', 'PR', 'BY', 'RU', 'PH', 'TH', 'AE', 'CO', 'ES', 'GB', 'AR', 'ID', 'NL','ES', 'IE', 'PK', 'AU', 'KW', 'SO')
 - Channel Name: Name of the channel
 - Category: Category ('Gaming & Apps','Sports', 'Music', 'Beauty & Fashion', 'Science & Tech', 'Fashion', 'LifeStyle')
 - Main Video Category: ('Music', 'Education', 'Shows', 'Gaming', 'Entertainment', 'People & Blogs', 'Sports', 'Howto & Style', 'Film & Animation', 'News & Politics', 'Pop music', 'Comedy', 'Nonprofits & Activism', 'Action-adventure game', 'Strategy video game', 'TV shows')
 - Username: Username of the youtube channel
 - Followers: No. of followers
 - Main topic: Topic that has been discussed more.
 - More Topics: Topics apart from main topic.
 - Likes: Total Likes
 - Boost Index: Boost index value.
 - Engagement Rate: Rate of engagement with the users.
 - Engagement Rate 60days: Rate of engagement with the users for 60 days
 - View: Total Views
 - Views. Avg: Average views
 - Avg. 1 Day: Average views for one day
 - Avg. 3 Day: Average views for 3 days
 - Avg. 7 Day: Average views for 7 days
 - Avg. 14 Day: Average views for 14 days
 - Avg. 30 Day: Average view for 30 days
 - Avg. 60 Day: Average view for 60 days
 - Comments Avg: Average comments.
 - Youtube Link: Link of the channel

## Очистка данных

<b>Первоначально импортируем все необходимые нам библиотеки:</b>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

<b>Сохраним данные в DataFrame и посмотрим информацию о нем:</b>

In [13]:
folders = Path.cwd()
file_name = Path(folders, 'top_200_youtubers.csv')

df = pd.read_csv(file_name)
size = df.shape
print(size)

(857, 22)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 857 entries, 0 to 856
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country                 707 non-null    object
 1   Channel Name            857 non-null    object
 2   Category                736 non-null    object
 3   Main Video Category     855 non-null    object
 4   username                857 non-null    object
 5   followers               857 non-null    int64
 6   Main topic              855 non-null    object
 7   More topics             855 non-null    object
 8   Likes                   857 non-null    float64
 9   Boost Index             857 non-null    int64
 10  Engagement Rate         855 non-null    float64
 11  Engagement Rate 60days  857 non-null    float64
 12  Views                   857 non-null    int64
 13  Views Avg.              855 non-null    float64
 14  Avg. 1 Day              494 non-null    float64
 15  Avg. 3 Day              652 non-null    float64
 16  Avg. 7 Day              741 non-null    float64
 17  Avg. 14 Day             779 non-null    float64
 18  Avg. 30 day             815 non-null    float64
 19  Avg. 60 day             857 non-null    float64
 20  Comments Avg            855 non-null    float64
 21  Youtube Link            857 non-null    object
dtypes: float64(11), int64(3), object(8)
memory usage: 147.4+ KB

In [11]:
df.head(10)

,Country,Channel Name,Category,Main Video Category,username,followers,Main topic,More topics,Likes,Boost Index,...,Views,Views Avg.,Avg. 1 Day,Avg. 3 Day,Avg. 7 Day,Avg. 14 Day,Avg. 30 day,Avg. 60 day,Comments Avg,Youtube Link
0,IN,T-Series,Gaming & Apps,Music,T-Series,220000000,Music of Asia,"Entertainment,Music of Asia,Music,Movies",1.602680e+09,83,...,195660744416,2.095329e+06,1.522448e+05,2134569.625,1.809830e+06,2.306178e+06,1.676330e+06,2.295416e+06,4493.984146,UCq-Fj5jknLsUf-MWSy4_brA
1,US,ABCkidTV - Nursery Rhymes,Gaming & Apps,Education,ABCkidTV - Nursery Rhymes,138000000,Movies,"Entertainment,Music,Movies",2.209901e+08,63,...,133025325473,7.027126e+07,1.837916e+06,1837916.000,4.891832e+06,7.052576e+06,1.265433e+07,1.572284e+07,146.700252,UCbCmjCuTUZos6Inko4u57UQ
2,IN,SET India,Gaming & Apps,Shows,SET India,137000000,Movies,"Entertainment,TV shows,Music,Movies",1.748752e+08,79,...,121741739317,1.095729e+05,NaN,586040.000,2.801276e+05,3.437881e+05,3.536019e+05,3.220336e+05,76.244316,UCpEhnqL0y41EpW2TvWAHD7Q
3,US,PewDiePie,Gaming & Apps,Gaming,PewDiePie,111000000,Lifestyle,"Gaming,Action game,Lifestyle,Action-adventure ...",2.191406e+09,88,...,28424113942,7.718345e+06,NaN,NaN,3.497395e+06,3.094440e+06,3.620274e+06,4.454120e+06,35839.781347,UC-lHJZR3Gqxm24_Vd_AJ5Yw
4,US,MrBeast,Gaming & Apps,Entertainment,MrBeast,98100000,Lifestyle,"Entertainment,Lifestyle,Technology",1.731833e+09,60,...,16242634269,9.876250e+07,NaN,NaN,2.994102e+07,2.994102e+07,2.994102e+07,5.343473e+07,113432.373684,UCX6OQ3DkcsbYNE6H8uQQuVA
5,US,Like Nastya,NaN,People & Blogs,Like Nastya,97300000,Hobby,"Lifestyle,Hobby",2.808777e+08,79,...,80111555805,1.381637e+08,NaN,3946868.000,5.829929e+06,9.480138e+06,1.375691e+07,2.210875e+07,0.292490,UCJplp5SjeGSdVdwsfb9Q7lQ
6,US,✿ Kids Diana Show,Gaming & Apps,Entertainment,✿ Kids Diana Show,97200000,Lifestyle,"Lifestyle,Hobby",2.351904e+08,67,...,77340155581,8.641735e+07,NaN,NaN,7.539490e+06,9.148088e+06,1.434739e+07,2.346710e+07,0.000000,UCk8GzjMOrta8yxDcKfylJYw
7,IN,T-Series,Gaming & Apps,Music,T-Series,220000000,Music of Asia,"Entertainment,Music of Asia,Music,Movies",1.602680e+09,83,...,195660744416,2.095329e+06,1.522448e+05,2134569.625,1.809830e+06,2.306178e+06,1.676330e+06,2.295416e+06,4493.984146,UCq-Fj5jknLsUf-MWSy4_brA
8,US,ABCkidTV - Nursery Rhymes,Gaming & Apps,Education,ABCkidTV - Nursery Rhymes,138000000,Movies,"Entertainment,Music,Movies",2.209901e+08,63,...,133025325473,7.027126e+07,1.837916e+06,1837916.000,4.891832e+06,7.052576e+06,1.265433e+07,1.572284e+07,146.700252,UCbCmjCuTUZos6Inko4u57UQ
9,IN,SET India,Gaming & Apps,Shows,SET India,137000000,Movies,"Entertainment,TV shows,Music,Movies",1.748752e+08,79,...,121741739317,1.095729e+05,NaN,586040.000,2.801276e+05,3.437881e+05,3.536019e+05,3.220336e+05,76.244316,UCpEhnqL0y41EpW2TvWAHD7Q

<b>Можно заметить, что в таблице встречаются дубликаты (0 и 7 строки). Удалим их:</b>

In [5]:
df = df.drop_duplicates().reset_index(drop=True)

In [6]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country                 164 non-null    object
 1   Channel Name            200 non-null    object
 2   Category                164 non-null    object
 3   Main Video Category     199 non-null    object
 4   username                200 non-null    object
 5   followers               200 non-null    int64
 6   Main topic              199 non-null    object
 7   More topics             199 non-null    object
 8   Likes                   200 non-null    float64
 9   Boost Index             200 non-null    int64
 10  Engagement Rate         199 non-null    float64
 11  Engagement Rate 60days  200 non-null    float64
 12  Views                   200 non-null    int64
 13  Views Avg.              199 non-null    float64
 14  Avg. 1 Day              117 non-null    float64
 15  Avg. 3 Day              153 non-null    float64
 16  Avg. 7 Day              172 non-null    float64
 17  Avg. 14 Day             182 non-null    float64
 18  Avg. 30 day             191 non-null    float64
 19  Avg. 60 day             200 non-null    float64
 20  Comments Avg            199 non-null    float64
 21  Youtube Link            200 non-null    object
dtypes: float64(11), int64(3), object(8)
memory usage: 34.5+ KB

(200, 22)

После удаления дубликатов размер таблицы заметно уменьшился. Однако видно, что в столбцах <b><i>Country, Category,Main vedio category, Main vedio topics, More topics, Engagement Rates,Views avg, Avg.1 Day,Avg. 3 Day, Avg. 7 Day, Avg. 14 Day, Avg. 30 Day, Comments Avg</i></b> присутствуют пустые значения. Их необходимо обработать.